### PR TITLE
Refactors using Interfaces

### PR DESCRIPTION
**Pull request by inf0rmer**

### CODE REVIEW

**Comment by inf0rmer** [comment]
@kartesus ping

**Comment by kartesus-zz** [comment]
Shouldn't `(a *Agent) Signal(event string, data interface{}) error` be part of the `MicrobrewAgent` interface?

It seems to me that being able to send signals is even more indicative of an agent then having an `Init` method.

Otherwise looks good to me :+1:

**Comment by inf0rmer** [comment]
Yup, that's right, just added it. Before merging can you figure out some steps that allow us to test this? I'm really confused about how to do it.

**Comment by kartesus-zz** [comment]
Changed a bit your refactor to make it easier to test. 

My strategy was to add `NewAgentForProducer(producer MicrobrewProducer) *Agent`. This allow us to mock `MicrobrewProducer` and test `(a *Agent) Signal(event string, data interface{}) error`.

Then I changed `(a *Agent) Init(uri, exchange, exchangeType string) error` to be

``` go
func NewAgent(uri, exchange, exchangeType string) *Agent {
  producer := NewProducer(uri, exchange, exchangeType)
  return NewAgentForProducer(producer)
 }
```

If the arguments have the right type it's proven (almost, I didn't test the producer yet) that it works. So we can rely on the compiler to check that.

What do you think?

**Comment by kartesus-zz** [comment]
Oh and I added Godeps to the project. The community is leaning towards this vendoring approach, so I think it's better to conform even if I don't like it.

Since this is an open source project, it would make sense to support http://gopkg.in. We just have to make tags when releasing new versions.

**Comment by inf0rmer** [comment]
I was using [GPM](https://github.com/pote/gpm) in the HTTP Gateway project, should we change everything to Godeps? Also, should Godeps be committed in the repo?

**Comment by inf0rmer** [comment]
Yup, I agree with the tags for versions thing :).

**Comment by inf0rmer** [comment]
The refactor looks great! It really is all about dependency injection in Go, isn't it?
:+1:

**Comment by kartesus-zz** [comment]
I didn't notice you used a different one. Because godep used to have that Godeps file. It looks like godep and gpm are the main contenders as "official" package manager. Godep looks to have a head because the community favours having the dependencies in source control.

I like godep better but wouldn't oppose to use gpm.

**Comment by inf0rmer** [comment]
We can switch to godep if you are more experienced with it, but [gpm also vendors dependencies (via gvp)](http://technosophos.com/2014/05/29/why-gpm-is-the-right-go-package-manager.html).

**Pull request merged**
